#!/bin/bash

JAVA_HOME=/home/takisd/Development/tools/java/jdk7
export JAVA_HOME

EQ_DIR=/home/takisd/Development/workspace/eclipse/ExecuteQuery
BUILD_DIR=$EQ_DIR/scripts/ExecuteQuery
OUTPUT_JAR=$BUILD_DIR/build/eq.jar

IDE_DIR=/home/takisd/Development/tools/ide/executequery

echo $BUILD_DIR

if [ -d $BUILD_DIR ]; then
    echo
    echo "Removing existing build dir..."
    rm -Rf $BUILD_DIR
    echo
fi

/home/takisd/Development/tools/ide/apache-ant-1.7.1/bin/ant

if [ -f $OUTPUT_JAR ]; then

    cp $IDE_DIR/eq.jar $IDE_DIR/eq.jar.1
    cp $OUTPUT_JAR $IDE_DIR
#    cp $OUTPUT_JAR /home/takisd/transfers/public
    rm -Rf $BUILD_DIR

fi

echo
echo -n "Do you wish to upload this latest build? (y/n) "
read ANSWER
echo

if [ $ANSWER = "y" -o $ANSWER = "Y" -o $ANSWER = "yes" -o $ANSWER = "YES" ]; then
    ./ftp-latest.sh
fi






