#!/bin/bash

JAVA_HOME=/home/takisd/softdev/dev-env/java/jdk6
export JAVA_HOME

EQ_DIR=/home/takisd/softdev/workspaces/eclipse/ExecuteQuery
BUILD_DIR=$EQ_DIR/scripts/ExecuteQuery
OUTPUT_JAR=$BUILD_DIR/build/eq.jar

IDE_DIR=/home/takisd/softdev/dev-env/ide/executequery

echo $BUILD_DIR

if [ -d $BUILD_DIR ]; then
    echo
    echo "Removing existing build dir..."
    rm -Rf $BUILD_DIR
    echo
fi

ant

if [ -f $OUTPUT_JAR ]; then

    cp $IDE_DIR/eq.jar $IDE_DIR/eq.jar.1
    cp $OUTPUT_JAR $IDE_DIR
    cp $OUTPUT_JAR /home/takisd/transfers/public
    rm -Rf $BUILD_DIR

fi


