#!/bin/bash

EQ=/home/takisd/softdev/workspaces/eclipse/ExecuteQuery
EQ_SRC=$EQ/src

UL_SRC=/home/takisd/softdev/workspaces/eclipse/UnderworldLabs/src

SF=/home/takisd/softdev/workspaces/eclipse/ExecuteQuery-SF
TEMP=$SF/temp
SF_SRC=$SF/java/src

cd $SF_SRC

for FILE in `find . -name *.java -type f`
do

    if [[ ! -f $EQ_SRC/$FILE && ! -f $UL_SRC/$FILE ]]; then

        rm -f $FILE

    fi

done

if [ ! -d $TEMP ]; then

    mkdir -p $TEMP

fi

cd $TEMP

if [ -d $TEMP/org ]; then
    
    rm -Rf org/

fi

echo
echo "copying and cleaning src..."
echo

cp -R $EQ_SRC/org .
cp -R $UL_SRC/org .

/home/takisd/bin/remove-cvs .
cp -R org $SF_SRC

rm $SF/lib/*.jar
cp $EQ/lib/*.jar $SF/lib

echo
echo "copying package files..."
echo

cp $EQ/dependencies.txt $SF/

TEMPLATE=$EQ/ant/template-build/src
cp $TEMPLATE/docs/eqhelp.jar $SF/package-files/docs
cp $TEMPLATE/docs/LICENSE $SF/package-files/docs
cp $TEMPLATE/docs/README $SF/package-files/docs
cp $TEMPLATE/apache.LICENSE $SF/package-files
cp $TEMPLATE/eq.exe $SF/package-files
cp $TEMPLATE/eq.ico $SF/package-files
cp $TEMPLATE/eq.l4j.ini $SF/package-files
cp $TEMPLATE/eq.png $SF/package-files
cp $TEMPLATE/eq.sh $SF/package-files
cp $TEMPLATE/eqhelp.exe $SF/package-files
cp $TEMPLATE/executequery.desktop $SF/package-files
cp $TEMPLATE/*.LICENSE $SF/package-files
cp $TEMPLATE/LICENSE $SF/package-files
cp $TEMPLATE/README.txt $SF/package-files
cp $TEMPLATE/uninstall.exe $SF/package-files
cp $TEMPLATE/uninstall.jar $SF/package-files
cp $TEMPLATE/uninstall.sh $SF/package-files

rm -Rf org
rm -Rf $TEMP

