#!/bin/bash

JAVA_HOME=/home/takisd/softdev/java/jdk1.5.0_18
PATH=$JAVA_HOME/bin:$PATH
export PATH JAVA_HOME

echo
echo "using java version:"
java -version

EQ_DIR=/home/takisd/temp/workspace4/ExecuteQuery
BUILD_DIR=$EQ_DIR/scripts/ExecuteQuery
OUTPUT_JAR=$BUILD_DIR/build/eq.jar

IDE_DIR=/home/takisd/softdev/ide/executequery

echo $BUILD_DIR

if [ -d $BUILD_DIR ]; then
    echo
    echo "Removing existing build dir..."
    rm -Rf $BUILD_DIR
    echo
fi

ant

if [ -f $OUTPUT_JAR ]; then

    cp $IDE_DIR/eq.jar $IDE_DIR/eq.jar.1
    cp $OUTPUT_JAR $IDE_DIR
    rm -Rf $BUILD_DIR

fi


