#!/bin/bash

cd $1

if [ -z $1 ]; then

    echo
    echo "please provide the driectory to scan"
    echo "exiting..."
    echo
    exit 1

fi

echo

for IMAGE in `ls *.png`
do 
    
    echo "converting $IMAGE"
    convert $IMAGE -blur 0x.35 $IMAGE

done





